### ISSUE TITLE
How to train this model on customized data (images)

### ISSUE THREAD

**Issue by soumya-ranjan-sahoo** [junyuchen245/Unsuprevised_Seg_via_CNN#5]
Hi,

Great work there with some impressive results!

I would like to use your model for my experiments with 3D thermographic images. Could you kindly guide me on how to run the model after cloning this repo?

I understand I have to run train.py as other files are already imported within it. 

Regarding the arrangement of my images, how should I go about this? May I know what images and how many of them are in each of these 4 directories? Can I train with just 1 image and test with another? 
imgDir = '/netscratch/jchen/SPECTSeg_data/train/'
gtDir = '/netscratch/jchen/SPECTSeg_data/train/'
imgTestDir = '/netscratch/jchen/SPECTSeg_data/test/'
gtTestDir = '/netscratch/jchen/SPECTSeg_data/test/'

Looking forward to hearing from you.

Thanks in advance!

**Comment by junyuchen245** [comment]
Hi,

I added another training script, "train_v2.py", that does not depend on "img_flow.py". You can define your image and ground truth file names in this script. The files have to be in the '.npz' format. Otherwise, you will have to modify the script. Keep in mind that the program iterates the first dimension (i.e., [slice,:,:]) of your image.

Thanks,
Junyu

**Comment by soumya-ranjan-sahoo** [comment]
Thank you very much for your comments.
I thought it is an unsupervised algorithm and therefore we might not need a
ground truth. Is the ground truth used by the algorithm?

Also can I just train the model with just 1 training image?

Your feedback is much appreciated.

Thank you.

Regards,
Soumya.

**Comment by junyuchen245** [comment]
Indeed, the ground truth for training is not required. If you see https://github.com/junyuchen245/Unsuprevised_Seg_via_CNN/blob/80bd03739866b29286b13ca19294cf2479d4dbc6/Unsupervised_Seg/train_v2.py#L140
, the GT image was not used in training. I have the GT there because I also tried semi-supervised version as described in my paper.

Yes, you can try training the network with a single image, but Idk how well it will work.

Thanks,
Junyu
